# arrays

In [1]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0, 11)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.38355409, 0.23745907, 0.09994232, 0.82184806, 0.37181678])

In [20]:
np.random.rand(5, 5)

array([[0.35699281, 0.73303945, 0.96174415, 0.11051507, 0.48183467],
       [0.6003059 , 0.35958602, 0.51611352, 0.89535899, 0.8634875 ],
       [0.11652529, 0.00960362, 0.1424752 , 0.10737107, 0.8983586 ],
       [0.33187277, 0.91897945, 0.71406268, 0.47194655, 0.87821933],
       [0.64608171, 0.56390363, 0.75507365, 0.86333521, 0.70958445]])

In [24]:
np.random.randint(1, 100)

12

In [25]:
np.random.randint(1, 100, 10)

array([64, 10, 20, 89, 32,  8, 96, 87, 13,  1])

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
random_arr = np.random.randint(0, 50, 10)

In [29]:
random_arr

array([26, 25, 40, 28, 35,  3, 21, 13, 17, 41])

In [30]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
random_arr.max()

41

In [32]:
random_arr.min()

3

In [33]:
random_arr.argmax()

9

In [34]:
random_arr.argmin()

5

In [35]:
arr.shape

(25,)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr = arr.reshape(5, 5)

In [38]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.shape

(5, 5)

In [40]:
arr.dtype

dtype('int64')

# indexing and selection

In [41]:
arr = np.arange(0, 11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[8]

8

In [44]:
arr[1:5]

array([1, 2, 3, 4])

In [45]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [46]:
arr[:5]

array([0, 1, 2, 3, 4])

In [47]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
slice_of_arr = arr[0:6]

In [49]:
slice_of_arr[:] = 99

In [50]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [51]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [52]:
slice_two = slice_of_arr[0:2]

In [53]:
slice_two[:] = 5

In [54]:
arr

array([ 5,  5, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_copy = arr.copy()

In [56]:
arr_copy

array([ 5,  5, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr_copy[:] = 100

In [58]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [59]:
arr

array([ 5,  5, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [61]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
arr_2d[0][0]

5

In [63]:
arr_2d[1][1]

25

In [64]:
arr_2d[2][1]

40

In [67]:
arr_2d[2, 1]

40

In [68]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [69]:
arr_2d[1]

array([20, 25, 30])

In [70]:
arr = np.arange(1, 11)

In [72]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [73]:
bool_arr = arr > 5

In [74]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [75]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [77]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [78]:
arr[arr < 3]

array([1, 2])

In [82]:
arr_2d = np.arange(50).reshape(5, 10)

In [83]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

# operations

In [84]:
arr = np.arange(0, 10)

In [85]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [87]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [88]:
arr / arr

/tmp/ipykernel_74706/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [89]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [90]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [91]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
1/0

ZeroDivisionError: division by zero

In [93]:
1 / arr

/tmp/ipykernel_74706/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [94]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [95]:
np.sqrt(arr ** 2)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [96]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [97]:
np.max(arr)

9

In [98]:
np.min(arr)

0

In [99]:
arr.max()

9

In [100]:
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [101]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [102]:
np.log(arr)

/tmp/ipykernel_74706/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# exercises

In [103]:
import numpy as np

In [105]:
zero_arr = np.zeros(10)

In [107]:
zero_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [108]:
ones_arr = np.ones(10)

In [109]:
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [110]:
fives_arr = np.ones(10) * 5

In [111]:
fives_arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [112]:
arr = np.arange(10, 51)

In [113]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [118]:
arr_even = np.arange(10, 51, 2)

In [119]:
arr_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [121]:
arr_matrix = np.arange(0, 9).reshape(3, 3)

In [122]:
arr_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [123]:
id_matrix = np.eye(3)

In [124]:
id_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
np.random.rand(1)

array([0.11937142])

In [129]:
np.random.rand(25)

array([0.20170349, 0.74609349, 0.95206908, 0.84680228, 0.88416138,
       0.37722612, 0.08789418, 0.94871809, 0.34390725, 0.48296721,
       0.53687453, 0.68303917, 0.51839316, 0.6613518 , 0.44238766,
       0.4520258 , 0.61696962, 0.7268806 , 0.33395277, 0.93952305,
       0.65209653, 0.42158314, 0.602623  , 0.11294099, 0.11349442])

In [135]:
np.linspace(0, 0.9999, 100).reshape(10, 10)

array([[0.    , 0.0101, 0.0202, 0.0303, 0.0404, 0.0505, 0.0606, 0.0707,
        0.0808, 0.0909],
       [0.101 , 0.1111, 0.1212, 0.1313, 0.1414, 0.1515, 0.1616, 0.1717,
        0.1818, 0.1919],
       [0.202 , 0.2121, 0.2222, 0.2323, 0.2424, 0.2525, 0.2626, 0.2727,
        0.2828, 0.2929],
       [0.303 , 0.3131, 0.3232, 0.3333, 0.3434, 0.3535, 0.3636, 0.3737,
        0.3838, 0.3939],
       [0.404 , 0.4141, 0.4242, 0.4343, 0.4444, 0.4545, 0.4646, 0.4747,
        0.4848, 0.4949],
       [0.505 , 0.5151, 0.5252, 0.5353, 0.5454, 0.5555, 0.5656, 0.5757,
        0.5858, 0.5959],
       [0.606 , 0.6161, 0.6262, 0.6363, 0.6464, 0.6565, 0.6666, 0.6767,
        0.6868, 0.6969],
       [0.707 , 0.7171, 0.7272, 0.7373, 0.7474, 0.7575, 0.7676, 0.7777,
        0.7878, 0.7979],
       [0.808 , 0.8181, 0.8282, 0.8383, 0.8484, 0.8585, 0.8686, 0.8787,
        0.8888, 0.8989],
       [0.909 , 0.9191, 0.9292, 0.9393, 0.9494, 0.9595, 0.9696, 0.9797,
        0.9898, 0.9999]])

In [136]:
np.linspace(0, 1, 20).reshape(4, 5)

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [140]:
matrix = np.arange(1, 26).reshape(5, 5)

In [141]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [142]:
selected_matrix = matrix[2: , 1:]

In [143]:
selected_matrix

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [144]:
matrix[3, 4]

20

In [145]:
selected_matrix[1, 3]

20

In [147]:
matrix[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [151]:
matrix[4:]

array([[21, 22, 23, 24, 25]])

In [152]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [153]:
matrix[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [154]:
matrix.sum()

325

In [155]:
matrix.std()

7.211102550927978

In [156]:
matrix.sum(axis=0)

array([55, 60, 65, 70, 75])

In [157]:
matrix.sum(axis=1)

array([ 15,  40,  65,  90, 115])