# arrays

In [1]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0, 11)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.38355409, 0.23745907, 0.09994232, 0.82184806, 0.37181678])

In [20]:
np.random.rand(5, 5)

array([[0.35699281, 0.73303945, 0.96174415, 0.11051507, 0.48183467],
       [0.6003059 , 0.35958602, 0.51611352, 0.89535899, 0.8634875 ],
       [0.11652529, 0.00960362, 0.1424752 , 0.10737107, 0.8983586 ],
       [0.33187277, 0.91897945, 0.71406268, 0.47194655, 0.87821933],
       [0.64608171, 0.56390363, 0.75507365, 0.86333521, 0.70958445]])

In [24]:
np.random.randint(1, 100)

12

In [25]:
np.random.randint(1, 100, 10)

array([64, 10, 20, 89, 32,  8, 96, 87, 13,  1])

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
random_arr = np.random.randint(0, 50, 10)

In [29]:
random_arr

array([26, 25, 40, 28, 35,  3, 21, 13, 17, 41])

In [30]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
random_arr.max()

41

In [32]:
random_arr.min()

3

In [33]:
random_arr.argmax()

9

In [34]:
random_arr.argmin()

5

In [35]:
arr.shape

(25,)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr = arr.reshape(5, 5)

In [38]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.shape

(5, 5)

In [40]:
arr.dtype

dtype('int64')

# indexing and selection

In [41]:
arr = np.arange(0, 11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[8]

8

In [44]:
arr[1:5]

array([1, 2, 3, 4])

In [45]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [46]:
arr[:5]

array([0, 1, 2, 3, 4])

In [47]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
slice_of_arr = arr[0:6]

In [49]:
slice_of_arr[:] = 99

In [50]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [51]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [52]:
slice_two = slice_of_arr[0:2]

In [53]:
slice_two[:] = 5

In [54]:
arr

array([ 5,  5, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_copy = arr.copy()

In [56]:
arr_copy

array([ 5,  5, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr_copy[:] = 100

In [58]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [59]:
arr

array([ 5,  5, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [61]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
arr_2d[0][0]

5

In [63]:
arr_2d[1][1]

25

In [64]:
arr_2d[2][1]

40

In [67]:
arr_2d[2, 1]

40

In [68]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [69]:
arr_2d[1]

array([20, 25, 30])

In [70]:
arr = np.arange(1, 11)

In [72]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [73]:
bool_arr = arr > 5

In [74]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [75]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [77]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [78]:
arr[arr < 3]

array([1, 2])

In [82]:
arr_2d = np.arange(50).reshape(5, 10)

In [83]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])